src/scss/tools/mixins/_type.scss
=> v0.4.1 – Fixing stack overflow exception when calling font-size with numbers directly

.travis.yml, CHANGELOG.md, gulpfile.js, package.json, src/scss/base/_typography.scss, src/scss/tools/functions/_units.scss, yarn.lock
- CHANGELOG (changelog inception ✨)
- Updated dependencies for `gulp-build-fozzie` and `fozzie-colour-palette`
- `hr` styling updated to use `border` rather than `background` as more native
- `@debug` statement in `line-height` function
=> v0.8.0 – Package updates and changelog added

.travis.yml, CHANGELOG.md, _build/config.js, package.json, src/scss/objects/_lists.scss, src/scss/objects/_tables.scss
- Lint task to run on travis so we can see any failures before they get published
- Couple of small updates in line with the linting errors
- Path for local scripts changed in line with new build config
=> v0.11.0 – Linting updates

CHANGELOG.md, package.json, src/scss/objects/_buttons.scss
- Changed default font-weight of `o-btn` to `500`
=> v0.18.1 - Adjusting default font-weight to 500

CHANGELOG.md, package.json, src/scss/trumps/_utilities.scss
Should we bump MINOR version or PATCH is enough for such change?
=> Added u-uppercase utility class

CHANGELOG.md, package.json, src/scss/trumps/_utilities.scss
Let me know if it should be moved to the different logical group.
=> Added u-pointer utility class

CHANGELOG.md, package.json
Prereq https://github.com/justeat/fozzie-colour-palette/pull/11
=> CPD-10667 fozzie-colour-palette version is bumped

.gitignore, CHANGELOG.md, package.json, src/scss/settings/_variables.scss, yarn.lock
- Added debug messages for passed in environment variables
- Updating `.gitignore` to exclude `yalc` config
=> v0.24.0 – Added debug messages for passed in environment variables

CHANGELOG.md, package.json, src/scss/objects/_buttons.scss
PR for issue described here: https://github.com/justeat/fozzie/issues/52
=> Fix submit button loader on Chrome for Android

CHANGELOG.md, package.json, src/scss/objects/_lists.scss
- List styling.  Indentation when text wrapped onto second line is now consistent and margin-top on nested lists removed (as not needed).
=> v0.26.0 List Indentation fixes

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/components/_media-element.scss
Direct port of media element with mixin updates where necessary for compatibility.
=> GS-375 Port media element over to Fozzie

.github/CODEOWNERS, CHANGELOG.md, LICENSE, dangerfile.js, package.json
- Dangerfile check to validate PR titles with respect to version numbers
- Basic CODEOWNERS file added
- Licence updated
=> v0.35.0 - Dangerfile check to validate PR titles with respect to version numbers and CODEOWNERS added

CHANGELOG.md, package.json, src/scss/objects/_form-controls.scss
call to zIndex variable was also including the $ when its not required too.
```
z-index: $zIndex(lowest);
```
=> v0.36.0 - fix to build of variable call of zIndex

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/components/_ratings.scss, src/scss/settings/_variables.scss, src/scss/tools/mixins/_index.scss, src/scss/tools/mixins/_ratings.scss
Ported over ratings for new selectable CSS stars without JS
Ported over existing ratings with couple more extenders
Tidied up existing CSS
=> v0.39.0 - selectable star ratings and non selectable star ratings

CHANGELOG.md, package.json, src/scss/base/_typography.scss, src/scss/objects/_lists.scss, src/scss/trumps/_utilities.scss
- `u-textPad` utility class added for padding text
- Updated ordered list styling
- Updated typography utility classes so that `.alpha`, `.beta`, `.gamma`, `.gamma` and `.delta` all match header styles when applied
=> v0.44.0 – Updates to typography and utility classes

CHANGELOG.md, package.json, src/scss/components/_cards.scss, src/scss/components/_listings.scss, src/scss/components/_ratings.scss, src/scss/tools/mixins/_border.scss, src/scss/tools/mixins/_index.scss, src/scss/trumps/_utilities.scss
_Update of Restaurant listing tile and associated components._
**Listing item with promo and address**
**Listing item with label and distance**
**Offline listing item with label and distance**
- iPhone 6s
=> v0.46.0 fozzie listing component

CHANGELOG.md, package.json, src/scss/base/_typography.scss
- Styling for address elements
---
=> v0.47.0 – Adding styling for address elements

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/components/_content-header.scss, src/scss/components/_serp-header.scss
_Creation of SERP header and variations._
- iPhone 7
=> v0.48.0 - Creation of SERP header and variations

CHANGELOG.md, package.json, src/scss/components/_listings.scss, src/scss/settings/_variables.scss
=> v0.49.0 listing component update

CHANGELOG.md, package.json, src/scss/base/_typography.scss
- Text utility classes for `text-highlight` and `text-indent`
=> v0.50.0 - Adding text-highlight and text-indent

CHANGELOG.md, package.json, src/scss/components/_ratings.scss
__*Patch to fix star rating count*__
- Change star count from 25 to 6
---
=> v0.50.1 - update count of rating fix, count 25 left over from tests

package.json
__*version bump in package.json*__
=> #trivial - package.json version bump

CHANGELOG.md, package.json, src/scss/components/_ratings.scss
Fixed stars look like selectable when the input is disabled.
If the input is disabled, stars won't lit on hover.
=> v0.53.1 - Fixed stars look like selectable when the input is disabled.

CHANGELOG.md, package.json, src/scss/trumps/_utilities.scss, yarn.lock
- Added spacing utility classes.
Closes #106.
=> v0.55.0 — Added spacing utility classes.

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/components/_badges.scss, src/scss/components/_cards.scss
- Optional `badge` component.
- `card` component modifiers.
- Applied relative position to `card` component.
=> v0.56.0 — Added badge component and updates cards component.

CHANGELOG.md, package.json, src/scss/components/_media-element.scss
- Media element element and modifier added.
=> v0.57.0 — Media element element and modifier added.

CHANGELOG.md, package.json, src/scss/components/_badges.scss
- New badge component modifiers
- Added prefix to badge component classes.
=> v0.58.0 — Updates to badge component.

CHANGELOG.md, package.json, src/scss/components/_media-element.scss
- Media element centered element.
=> v0.60.0 — Added media element centered element.

.travis.yml, CHANGELOG.md, README.md, package.json, yarn.lock
- Coveralls and packagephobia badges.
- Updated Travis config.
=> v0.60.1 — Added badges and updated Travis config.

CHANGELOG.md, README.md, package.json
- Updated Jest coverage directory.
- Packagephobia badge.
=> v0.60.2 —  Updated Jest coverage directory & removed readme badge.

CHANGELOG.md, package.json, src/scss/base/_layout.scss, src/scss/components/_media-element.scss, src/scss/trumps/_utilities.scss
- Centre align utility.
- No underline utility.
- Media element centered element.
=> v0.61.0 — Added new utility helpers.

CHANGELOG.md, package.json, src/img/decoration/rays--white--small.svg, src/img/decoration/rays--white.svg
- Decoration images.
- Copy assets config from `package.json`.
=> v0.63.0 — Removed decoration images.

CHANGELOG.md, package.json, src/scss/components/_badges.scss
- Spacing between spans inside the `c-badge` component.
=> v0.64.0 — Added spacing between spans inside the `c-badge` component.

CHANGELOG.md, package.json, src/scss/components/_badges.scss, src/scss/components/_cards.scss, src/scss/components/_page-banner.scss
- Changed page banner image media query.
- Updated component documentation.
=> v0.65.0 — Updated page banner image media query, and updated docs.

CHANGELOG.md, package.json, src/scss/settings/_variables.scss
- Updated heading font weight to match latest UI designs.
=> v0.68.0 — - Updated heading font weight to match latest UI designs.

CHANGELOG.md, package.json, src/scss/settings/_variables.scss
=> Revert "v0.68.0 — - Updated heading font weight to match latest UI designs."

CHANGELOG.md, package.json, src/scss/components/_badges.scss
- Added `c-badge--success`.
- Added `c-badge--important`.
- Added `c-badge--award`.
- Added `c-badge--angled`.
- Updated `c-badge` padding.
=> v0.69.0 — Badge component updates.

CHANGELOG.md, package.json, src/scss/components/_badges.scss, src/scss/trumps/_utilities.scss
- Added `u-spacingTop--large` utility class.
- Applied border radius to angled badges.
=> v0.70.0 — Added `u-spacingTop--large` utility class.

CHANGELOG.md, package.json, src/scss/components/_menu.scss
- Menu component now using borders rather than box-shadow.
=> v0.77.0 — Updated menu component.

CHANGELOG.md, package.json, src/scss/components/_cards.scss, src/scss/components/_menu.scss, src/scss/components/_page-banner.scss
- Card component section child styles.
=> v0.78.0 — Card component section child styles.

CHANGELOG.md, package.json, src/scss/components/_cards.scss, src/scss/settings/_variables.scss
- No padding collapsible card section styles.
- Updated menu styles.
=> v0.79.0 — Updated menu styles.

CHANGELOG.md, package.json, src/scss/components/_listings.scss
- addition of alert status on listing text. 
- remove of unused var names within listing component
=> v0.84.0 - Listing alert text and clean up

CHANGELOG.md, package.json, src/scss/objects/_buttons.scss
- addition of cursor pointer to o-btnLink on hover, thats all.
=> v0.86.0 - addition of cursor pointer to o-btnLink on hover

CHANGELOG.md, package.json, src/scss/components/_badges.scss, src/scss/components/_cards.scss, src/scss/trumps/_utilities.scss
- Card component normalise links modifier.
- Position sticky utility helper.
- Padding utility helpers.
- Applied `!important` declaration to spacing utilities to ensure that they always trump other styles.
- Badge component text never wraps.
- Increased spacing between badges.
- Card components display as blocks.
- Card component comments updated.
- Overlap of angled badge section over text.
=> v0.87.0 — Updating card and utilities.

CHANGELOG.md, package.json, src/scss/components/_badges.scss, src/scss/components/_listings.scss
- Addition of height to - c-listing-item-premier height
=> v0.91.0 - c-listing-item-premier height

CHANGELOG.md, package.json, src/scss/base/_layout.scss, src/scss/components/_cards.scss, src/scss/trumps/_utilities.scss
- `l-inlined--top` layout helper.
- `c-badge--alignCenter` badge modifier.
- New card modifiers for spacing, borders, and background colours.
- Utility helper for text truncation.
=> v0.92.0 — Updated components and added new utility helpers.

CHANGELOG.md, package.json, src/scss/trumps/_utilities.scss
😭 
Unsure why github didn't pick this up - I missed off a trailing semi colon though
=> v0.97.1 - addition of trailing semi-colon

CHANGELOG.md, package.json, src/scss/components/_badges.scss, src/scss/components/_media-element.scss, src/scss/components/_menu.scss, src/scss/components/_page-banner.scss
- Media element negative image position.
- Top menu spacing.
- Page banner positions.
- Badge separator display fix.
=> v0.102.0 — Component style updates.

CHANGELOG.md, package.json, src/scss/components/optional/_listings.scss, src/scss/components/optional/_overflow-carousel.scss, yarn.lock
- Fix spacing on `c-listing` component. 
- Fix display type on `c-overflowCarousel` component
=> v1.2.0 - Fixes to c-listing and c-overflowCarousel

CHANGELOG.md, package.json, src/scss/settings/_variables.scss
- addition of new value `belowHighest` to zIndex map
=> v1.7.0 - addition of new value `belowHighest` to zIndex map

CHANGELOG.md, package.json, src/js/modules/breakpointHelper.js
- change switch to obj literal for better performance / readability
=> v1.14.1 - remove switch and replace with object literal

CHANGELOG.md, package.json, src/scss/components/_breadcrumbs.scss
v1.15.0 - Added compact breadcrumbs and fixed breadcrumbs styling
Also fixes https://github.com/justeat/fozzie/issues/97
=> v1.15.0 - Added compact breadcrumbs and fixed breadcrumbs styling

CHANGELOG.md, package.json, src/scss/components/optional/_page-banner.scss, src/scss/settings/_variables.scss
- Expand styles for `c-pageBanner` to become more reusable
=> v1.16.0 - expand styles for c-pageBanner

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/base/_layout.scss, src/scss/components/optional/_order-card.scss, src/scss/components/optional/_overflow-carousel.scss, src/scss/components/optional/_previous-order-card.scss, yarn.lock
- Styles for `c-orderCard`.
Layout can be checked in [this PR](https://github.com/justeat/global-component-library/pull/74)
Scrolling:
[![Image from Gyazo](https://i.gyazo.com/cde2f54d00da1e470d9bfff7427c8a5c.gif)](https://gyazo.com/cde2f54d00da1e470d9bfff7427c8a5c)
Hover:
[![Image from Gyazo](https://i.gyazo.com/16ee583fd1b62ec477812382d747b471.gif)](https://gyazo.com/16ee583fd1b62ec477812382d747b471)
=> v1.19.0 - styles for order card component

CHANGELOG.md, README.md, package.json, src/scss/components/_cards.scss
- LGTM badge on readme.
- Updated readme layout.
- Hide first of type paragraph in a collapsed card section.
=> v1.22.0 — Hide first of type paragraph in a collapsed card section.

CHANGELOG.md, package.json, src/scss/components/_cards.scss
- Adjusted collapsible card padding and heights for different device widths.
=> v1.23.0 — Adjusted collapsible card padding and heights for different device widths.

CHANGELOG.md, package.json, src/scss/base/_layout.scss, src/scss/components/optional/_apps-banner.scss
- `l-innerContainer--verticalSpacing` for base spacing between sections.
=> v1.24.0 modifier class for base spacing between sections

CHANGELOG.md, package.json, src/scss/components/optional/_order-card.scss, src/scss/components/optional/_overflow-carousel.scss, src/scss/objects/_links.scss
- Fix some styles for `c-orderCard` and `c-overflowCarousel` components
- `.o-tile-link` class
=> v1.29.0 small styles tweaks for c-orderCard and c-overflowCarousel

CHANGELOG.md, package.json, src/scss/components/optional/_overflow-carousel.scss
- Centre align child elements in `c-overflowCarousel` component
- Adjust spacing around the `c-overflowCarousel` component
=> v1.29.1 Centre align child elements in c-overflowCarousel component

CHANGELOG.md, package.json, src/scss/base/_layout.scss, src/scss/components/optional/_page-banner.scss
- `l-container` media queries breakpoints
- `c-pageBanner` small styles amends
=> v1.32.0 l-container breakpoints and c-pageBanner styles fixes

CHANGELOG.md, package.json, src/scss/components/optional/_order-card.scss, src/scss/trumps/_utilities.scss
=> v1.35.0 Styles for c-orderCard--noOpenRestaurants

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/components/optional/_menu.scss, src/scss/components/optional/_modal.scss, src/scss/trumps/_utilities.scss
- Modal optional component.
- Expandable menu modifier.
- Overlay & prevent scroll utility helpers.
- Menu component `has-icon` class only applied to small device widths.
=> v1.36.0 — Adding new components & utilities.

CHANGELOG.md, package.json, src/scss/components/optional/_modal.scss, yarn.lock
- Updated npm dependencies.
- Modal styles which caused the modal to be hidden on large screens.
=> v1.40.0 — Modal style fix and npm updates.

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/components/optional/_listings-skeleton.scss
_Added c-listing-skeleton component_
Desktop:
Mobile:
=> v1.41.0 - Added c-listing-skeleton component

CHANGELOG.md, package.json, src/scss/components/optional/_badges.scss
- OK, dark, and indicator badge modifiers.
=> v1.42.0 — Added OK, dark, and indicator badge modifiers.

CHANGELOG.md, package.json, src/scss/components/optional/_modal.scss
=> v1.44.0 — Updated modal transition time.

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/components/optional/_user-message.scss
Styles for user message component.
=> v1.47.0 - Add user message component

CHANGELOG.md, package.json, src/scss/components/optional/_listings.scss
Added c-listing-item-promo-text--earned style to be used on `SearchWeb` component
=> v1.52.0 – Added c-listing-item-promo-text--earned style

CHANGELOG.md, package.json, src/scss/components/optional/_listings.scss
- Update `c-listing` component to reflect new design
=> v1.54.0 - Update `c-listing` component to reflect new design

CHANGELOG.md, package.json, src/scss/settings/_variables.scss
- Tweakpoint for `narrowMid: 600px` added to breakpoints
=> v1.55.0 – Adding tweakpoint for narrowMid to breakpoints

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/components/optional/_cuisines-collage.scss
This has been reviewed and approved on an internal PR already by @kevinrodrigues and @ashleynolan.
=> v1.56.0 - Adding styles for the cuisineCollage.

CHANGELOG.md, package.json, src/scss/components/_breadcrumbs.scss
=> v1.58.0 - Added c-breadcrumb--pill breadcrumb style.

CHANGELOG.md, package.json, src/scss/components/_cards.scss, src/scss/components/optional/_listings.scss
Updated collapsible card styles
=> v1.59.0 — Updated collapsible card styles.

CHANGELOG.md, package.json, src/scss/components/optional/_modal.scss
Adds modal styles. See changelog.
=> v1.60.0 - Add modal flush and scrollable styles.

CHANGELOG.md, package.json, src/scss/components/optional/_listings.scss
- addition of will change to c-listing-header to stop larger redraw
=> v1.62.0 - Stop c-listing-item larger redraw

CHANGELOG.md, package.json, src/scss/components/optional/_modal.scss
- Hide overflow on `c-modal-content` class.
=> v1.64.0 — Hide overflow on modal content class.

CHANGELOG.md, package.json, src/scss/components/optional/_order-card.scss, src/scss/components/optional/_overflow-carousel.scss
- Order card updated for Recent Orders and Favourites component
=> v1.65.0 – Order card updated for Recent Orders and Favourites component

CHANGELOG.md, package.json, src/scss/components/optional/_cuisines-widget.scss
- Updated popular cuisines component styling (as it moves from a list of cuisines to a carousel)
=> v1.68.0 - Updating popular cuisine component styles

CHANGELOG.md, package.json, src/scss/components/optional/_modal.scss, src/scss/components/optional/_toast.scss
- Updated modal styles.
- Set `z-index` value for toast component to ensure it is always visible.
=> v1.69.0 — Updating modal and toast styles.

CHANGELOG.md, package.json, src/scss/settings/_variables.scss
=> v1.70.0 -- Added new variable for z-index

CHANGELOG.md, package.json, src/scss/components/_media-element.scss, src/scss/components/optional/_modal.scss, src/scss/components/optional/_order-card.scss
- Order card updated for Your Favourites rollout
=> v1.72.0 -- Updated orderCard component for Your Favourites rollout

CHANGELOG.md, package.json, src/scss/components/optional/_modal.scss
=> v1.73.0 --- added new fixed class

CHANGELOG.md, package.json, src/scss/components/optional/_menu.scss
- Menu style indentation.
- Menu link active style.
=> v1.75.0 - Minor updates.

CHANGELOG.md, package.json, src/scss/components/_media-element.scss, src/scss/components/optional/_ratings.scss
- Styles to include review stars for Menulog
=> v1.76.2: Added styles for Menulog review stars

CHANGELOG.md, package.json, src/scss/components/optional/_order-card.scss
=> v1.78.0: Fix OrderCard Styling for yourFavourites Experiment

CHANGELOG.md, package.json, src/scss/components/_media-element.scss
- Styles for `c-mediaElement-img--negativeTop` and `c-mediaElement-heading`
=> v1.79.0: Changed styles for menuweb

CHANGELOG.md, package.json, src/scss/components/_media-element.scss, src/scss/components/optional/_menu.scss, src/scss/components/optional/_toast.scss
- Media element style changes reverted.
- Toast styles updated.
- Undefined variable reference fixed.
=> v1.80.0 - Updated styles.

CHANGELOG.md, package.json, src/scss/components/_cards.scss, src/scss/components/optional/_badges.scss, src/scss/components/optional/_modal.scss, src/scss/trumps/_utilities.scss
- `c-badge` component small rounded modifier styles.
- `u-spacingBottom--large--aboveMid` & `u-shadowBottom--belowMid` helper to the utilities.
- Updated `c-card` component highlight modifier styles.
- Updated `c-modal` component styles.
- Consistent spacing between rules in the utilities module.
- `c-card` component large rounded modifier styles.
=> v1.82.0 - Component updates.

CHANGELOG.md, package.json, src/scss/components/_cards.scss, src/scss/components/optional/_badges.scss
- Reverted previous change to badge style.
- Use explicit value for card rounded variable.
=> v1.83.1 - Minor updates.

CHANGELOG.md, package.json, src/scss/components/_cards.scss
- Updated card section styles.
=> v1.84.0 — Updated card section styles.

CHANGELOG.md, package.json, src/scss/components/optional/_overflow-carousel.scss
=> v1.85.0 - Update overflow-carousel

CHANGELOG.md, package.json, src/scss/components/optional/_modal.scss
- New class `c-modal-content-scrollHeight` for the scroll height of the mega modal
=> v1.86.0: New class for the scroll height

CHANGELOG.md, package.json, src/scss/components/optional/_modal.scss, src/scss/components/optional/_overflow-carousel.scss
- Height to `is-fixed` class again
=> v1.87.0: Added height back into fixed class

CHANGELOG.md, package.json, src/scss/objects/_buttons.scss
- New colors for button `:hover` and `:focus`
=> v1.90.0: Changed button colour for menulog

CHANGELOG.md, package.json, src/scss/components/optional/_modal.scss
- Moved modal close button to the left slightly.
- Transitions from modal.
=> v1.91.0 - Modal style updates.

CHANGELOG.md, package.json
- Added `prepare` task back in.
=> v1.91.1 - Added prepare task back in.

CHANGELOG.md, jest.config.js, package.json, yarn.lock
**Fixed**
- Updated jest.config.js (replaced a "|" with ",") so that tests are now detected
=> v2.2.0 - Updated jest.config.js

CHANGELOG.md, package.json, src/scss/settings/_variables.scss
- Additional spacing properties to the SCSS variables added.
=> v2.3.0 – Added additional spacing properties to the SCSS variables

CHANGELOG.md, babel.config.js, package.json, src/js/modules/stopFoit/test/index.test.js, src/scss/_dependencies.scss, src/scss/objects/_buttons.scss, src/scss/objects/_form-controls.scss, src/scss/objects/_lists.scss, src/scss/settings/_variables.scss, yarn.lock
- Updated Menulog theme to include first batch of Takeaway.com brand changes. Buttons, links and base colours all updated.
=> v3.0.0-beta.0 – Updated Menulog theme to include first batch of Takeaway.com brand changes

CHANGELOG.md, package.json, src/scss/_dependencies.scss
=> v3.0.0-beta.3 – Glaze theme mixin re-added

CHANGELOG.md, package.json, src/scss/objects/_buttons.scss, src/scss/settings/_variables.scss
- More glaze stuff re-added (doh).
=> v3.0.0-beta.4 - More glaze variables re-added

CHANGELOG.md, package.json, yarn.lock
- Update `fozzie-colour-palette` to latest version.
=> v3.0.0-beta.7 - Updating `fozzie-colour-palette` to latest version

CHANGELOG.md, package.json, src/scss/objects/_buttons.scss
- btn-default-weight now 600 for new font
=> v4.0.0-beta.1 - Updating button font weight

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/components/optional/_loading-indicator.scss
- `loading-indicator` styles which provides a spinner/loading style.
Example:
https://www.loom.com/share/8703016f3e434b079d2564417475b76e
=> v4.3.0 - Add loading indicator styles.

CHANGELOG.md, package.json
- Eyeglass version bumped to v3.
=> v5.0.0-beta.1 - Updating eyeglass version

CHANGELOG.md, package.json, yarn.lock
- Updated versions of `f-utils` and `fozzie-colour-palette` and other minor deps.
=> v5.0.0-beta.2 - Updating dependencies

CHANGELOG.md, package.json, yarn.lock
- Latest colour-palette pulled in and some minor package updates.
=> v4.4.0 – Updating colour-palette and minor dependencies

CHANGELOG.md, package.json, src/scss/trumps/_rwd.scss
- `.u-showAboveNarrow` class to include 414px in media query
=> v4.4.1 - .u-showAboveNarrow class to include 414px in media query

CHANGELOG.md, package.json, src/scss/components/optional/_apps-banner.scss
The new apps banner image is much more narrow than the old one, so we need to update `max-width`
**New apps banner preview:**
Jamie-Louise confirmed that we're switching to phone assets for both desktop and mobile versions.
=> v4.5.0 - Change max-width of apps banner image

CHANGELOG.md, package.json, yarn.lock
=> v5.0.0-beta.10 - pie-design-tokens package update

CHANGELOG.md, package.json, src/scss/base/_typography.scss
- body font size from 14px/0.875rem to 16px/1rem
=> v6.0.0-beta.5 - increase body font size to 16px/1rem

CHANGELOG.md, package.json, src/scss/components/optional/_tag.scss
- `c-tag` white modifier as per PIE designs.
=> v6.1.0 - Adding tag modifier.

CHANGELOG.md
=> #trivial - fix changelog instructions.

CHANGELOG.md, package.json, yarn.lock
- f-utils version to fix scss lint error.
=> v7.1.0 - Bump f-utils package.

CHANGELOG.md, package.json, yarn.lock
- f-utils version to fix further scss lint error.
=> v7.2.0 - f-util package bump.

CHANGELOG.md, package.json, src/scss/_dependencies.scss, src/scss/tools/_index.scss, src/scss/tools/functions/_index.scss, src/scss/tools/functions/_px-to-em.scss, src/scss/tools/functions/_spacing.scss, src/scss/tools/functions/_strip-units.scss, src/scss/tools/functions/_units.scss, src/scss/tools/functions/_zIndex.scss, src/scss/tools/helpers/_breakpoints.scss, src/scss/tools/helpers/_code-highlighting.scss, src/scss/tools/mixins/_alerts.scss, src/scss/tools/mixins/_border.scss, src/scss/tools/mixins/_index.scss, src/scss/tools/mixins/_ratings.scss, src/scss/tools/mixins/_truncate.scss, src/scss/tools/mixins/_type.scss
- f-utils `functions`, `helpers` & `mixins` in order to depreciate `f-utils` in favour of `fozzie`.
=> v8.1.0 - port over f-utils scss.

CHANGELOG.md, package.json, src/scss/base/_layout.scss, src/scss/objects/_buttons.scss
=> v9.0.0-beta.1 - Fixed mixin reference.

CHANGELOG.md, package.json, src/scss/base/_grid.scss, src/scss/tools/mixins/_type.scss, src/test/scss/tools/mixins/type.spec.scss
- `throw` usage and updated tests accordingly.
- `$fozzie-breakpoints` reference.
=> v9.0.1 - Fix up throw error.

CHANGELOG.md, package.json, yarn.lock
v9.3.1
*August 31, 2022*
- Updated to newer version of `stylelint-config-fozzie` package
=> v9.3.1 - update stylelint-config-fozzie version

CHANGELOG.md, package.json, src/scss/components/_media-element.scss
=> v9.3.2 - Fix SCSS math division warning.

CHANGELOG.md, package.json, src/scss/components/optional/_ratings.scss
- Ratings `extend` back in as a short term fix for consuming applications.
=> v10.1.0 - Adds rating styles back in.

CHANGELOG.md, package.json, src/scss/trumps/_utilities.scss
- Reverted box-shadow to custom value.
| Before | After |
| --- | --- |
| ![Screenshot 2022-09-29 at 15 12 12](https://user-images.githubusercontent.com/89059/193055184-b9cc973b-efe1-4ba7-9041-13f3da03bfe4.png)  | ![Screenshot 2022-09-29 at 15 12 33](https://user-images.githubusercontent.com/89059/193055229-ead589f8-80b0-49d1-889e-31bf7954cba3.png) |
=> v10.5.0 - Revert box-shadow to custom value.
