- CHANGELOG.md
- _build/config.js
- package.json
- src/scss/base/_layout.scss
- src/scss/base/_typography.scss
- src/scss/objects/_lists.scss
- src/scss/settings/_variables.scss
- src/scss/trumps/_utilities.scss
- yarn.lock
- Custom bullets on unordered lists.
- `u-bordered` class for adding a border around a block.
- Added narrow view type sizes for headings
- Updated line-height for jumbo homepage text.
- Updated the `l-content` class so that it can contain a `header` and `main` that are appropriately spaced for content pages.
- Updated packages
> v0.10.0 – Content classes updated, jumbo text line-height, and custom bullets

- CHANGELOG.md
- package.json
- src/scss/base/_layout.scss
- src/scss/trumps/_utilities.scss
- yarn.lock
- `:focus` state added (controlled via colour palette variable).
> v0.17.0 - focus state added to fozzie defaults

- CHANGELOG.md
- package.json
- src/scss/trumps/_utilities.scss
- `:focus` state updated to be `2px solid` rather than `3px auto` by default.
> v0.17.1 - Updating focus styling

- CHANGELOG.md
- package.json
- src/scss/trumps/_utilities.scss
Looks better than default outline on elements with rounded corners
> Focus outline emulation using box-shadow

- CHANGELOG.md
- package.json
- src/scss/objects/_buttons.scss
- src/scss/objects/_tables.scss
+ ### Added
+ - `.not-stripped` class to the table.
+ - `.is-loading` class to the o-btn.
Is it ok to keep the icon on the cdn? 
We don't have svg.
Or shall I move it to fa-icons project (which only have svgs at the moment) ?
> CPD-8233 Order Confirmation page additions

- .babelrc
- CHANGELOG.md
- package.json
- yarn.lock
- Updated `browserlist` in `package.json`
- Updated to use `babel-preset-env`
> CPD-11417 – Switch to using `babel-preset-env`

- CHANGELOG.md
- package.json
- src/scss/objects/_buttons.scss
Fixed o-btnLink's background-color for different statuses
It was putting grey background on hover:
> CPD-10667 Fixed o-btnLink's background-color for different statuses

- CHANGELOG.md
- package.json
- src/scss/components/_breadcrumbs.scss
Update to replace css 'inlined' svgs with svg icons for the breadcrumb component.
> Update to replace css inlined svgs that are breaking build

- CHANGELOG.md
- package.json
- src/scss/objects/_tables.scss
The problem happens when the first TD contains something like `<td rowspan="8">` which then causes the border to be missing on the rows below it because it treats the remaining TDs as a first-child. I've reversed the border to fix this issue.
> v0.37.0 - Fix applied to table border style.

- CHANGELOG.md
- package.json
- src/scss/objects/_buttons.scss
Changing the country selector from a link to a button disabled the outline on focus. This adds is back to make it more obvious, rather than just the hard-to-spot grey -> blue text colour change.
(And fix whitespace in changelog)
> v0.41.1 - Bring back the focus outline for the footer country selector

- CHANGELOG.md
- package.json
- src/scss/components/_fullscreen-pop-over.scss
- src/scss/objects/_form-toggle.scss
_Addition of form toggle disabled state and touch area size._
- height unit on fullScreenOverlay
- addition of .o-formToggle--disabled state styles
- addition of form toggle inline spacing to give 44px touch area
- addition of cursor pointer of form toggle hover
> v0.53.0 – Addition of form toggle disabled state and touch area size

- CHANGELOG.md
- package.json
- src/scss/objects/_form-toggle.scss
_Fix formToggle hover states._
On mobile hover state would hang when checking a checkbox. Design asked for hover state to only apply when >=mid.
before (Hover/checked mobile):
After checked:
> v0.53.2 - Fix formToggle states on mobile

- CHANGELOG.md
- package.json
- src/scss/components/_fullscreen-pop-over.scss
_Fix of fullscreen popover background colour._
Background colour has changed to grey-offWhite instead of white. 
background colour of parent and header/footer updated.
> v0.53.3 - fullscreen popover background colour fixes

- CHANGELOG.md
- package.json
- src/scss/objects/_form-toggle.scss
__*Convert form toggle tick from CSS created tick to f-icon asset*__
Before:
After:
---
> v0.53.4 form toggle icon

- CHANGELOG.md
- package.json
- src/scss/components/_listings.scss
__*addition of has-no-match styling to c-listing component*__
Before:
After:
> v0.54.0 - addition of has-no-match styling to c-listing component

- CHANGELOG.md
- package.json
- src/scss/components/_content-title.scss
__*Content Title Action hover state*__
- change text decoration of content header from none to underlined on hover
Before:
After:
---
> v0.59.1 - Content Title Action hover state

- CHANGELOG.md
- package.json
- src/scss/components/_listings.scss
_Update to listing tile._
Before:
After:
> v0.67.0 - updates to listing item

- CHANGELOG.md
- package.json
- src/scss/_dependencies.scss
- src/scss/base/_layout.scss
- src/scss/components/_menu.scss
- src/scss/tools/mixins/_truncate.scss
Queued behind #130.
- Optional `c-menu` component.
- `l-inlined` extended so that it can be referenced as a placeholder.
- Applied `z-index` to `c-pageBanner` component.
- `$truncation-boundary` parameter is now optional on the `truncate` mixin.
> v0.73.0 — Added Optional `c-menu` component.

- CHANGELOG.md
- package.json
- src/scss/components/_badges.scss
- src/scss/components/_listings.scss
- Removed styles from listing component so we can utilise c-badge
- Added `c-listing-item-premier` (Local legend badge) styling
> v0.74.0 - listing badge style amends 

- CHANGELOG.md
- package.json
- src/scss/components/_fullscreen-pop-over.scss
- Fixed  popOver content styles to media breakpoint to stop content being hidden by overflow
Before:
After:
> v0.74.1 - popOver content inside breakpoint

- CHANGELOG.md
- package.json
- src/scss/objects/_form-toggle.scss
- Updated formToggle count styling
- Changed formToggle large touch area class to target mobile only
[no visual change]
> v0.76.0 - updated formToggle count styling and touch area

- CHANGELOG.md
- package.json
- src/scss/components/_cards.scss
- src/scss/components/_listings.scss
- src/scss/components/_media-element.scss
- src/scss/components/_menu.scss
- src/scss/objects/_form-toggle.scss
- src/scss/settings/_variables.scss
- Card no padding modifier.
- Card highlight modifier.
- Card bottom section modifier.
- Animation to card section chevron.
- 0.5 spacing value.
- Updated modules to use new 0.5 spacing value.
- Card section margin only applied on larger screens.
> v0.80.0 — Card styles updated.

- CHANGELOG.md
- package.json
- src/scss/components/_overflow-carousel.scss
- src/scss/objects/_form-toggle.scss
- Updated formToggle click area.
- Removed formToggle count pointer events.
- Updated overflowCarousel display to `inline-flex`.
> v0.85.0 - formtoggle click area - overflow carousel display type

- CHANGELOG.md
- package.json
- src/scss/components/_badges.scss
- addition of c-badge--transparent modifier
Addition of `c-badge--transparent` modifier to remove the background. I needed the badge BG removed as on some c-listings states (offline has a rgba .5 background and causes issues).
Before:
After:
- Docs PR here:
- https://github.com/justeat/global-component-library/pull/56
> v0.88.0 - addition of c-badge--transparent modifier

- CHANGELOG.md
- package.json
- src/scss/components/_badges.scss
- remove margin from span within `c-badge`
*The changes have been approved by menu designers*
Before:
After:
> v0.90.0 - remove margin from span within `c-badge`

- CHANGELOG.md
- package.json
- src/scss/components/_listings.scss
- src/scss/objects/_form-toggle.scss
- Added addition focus states to improves accessibility of formToggles.
- Moved the padding from c-listing-item to c-listing-item-link for a nicer focus border look.
Before:
After:
> v0.93.0 - Focus states

- CHANGELOG.md
- package.json
- src/scss/components/_content-header.scss
- Made responsive breakpoints more consistent on `c-contentHeader`
Before:
After:
> v0.94.0 - content header responsiveness

- CHANGELOG.md
- package.json
- src/scss/components/_fullscreen-pop-over.scss
- update hover states on pop over action button
Before:
After:
> v0.98.0 - update hover states on pop over action button

- CHANGELOG.md
- package.json
- src/scss/components/_fullscreen-pop-over.scss
- src/scss/components/_listings.scss
- Update listing premier image selector [need to target SVG due to f-icons issue]
- Display none popover content to stop the user getting tabs lost in the popovers when they are not shown
[No visible change]
> v0.99.0 - listing SVG fix and improved accessibility on popovers

- CHANGELOG.md
- package.json
- src/scss/components/_content-header.scss
- fix content header link display property
Before:
After:
---
> v0.99.1 - fix content header link display property

- CHANGELOG.md
- package.json
- src/scss/components/_fullscreen-pop-over.scss
- Addition of modifier on `c-fullScreenPopOver` to stop non tabable functionality affecting other devices >mid
> v0.99.2 - no tab popover

- CHANGELOG.md
- package.json
- src/js/index.js
- src/js/modules/stopFoit/index.js
- src/js/modules/stopFoit/test/index.test.js
- src/scss/base/_typography.scss
- src/scss/settings/_variables.scss
- yarn.lock
- Stop FOIT JS module to reduce meaningful paint with webfonts
**Before (slow 3g):**
**After (slow 3g):**
- formToggle count text size
> v0.100.0 - addition of stopFOIT module and unit tests

- CHANGELOG.md
- package.json
- src/scss/base/_typography.scss
- src/scss/settings/_variables.scss
- update headings to use heading font weight variable.
- change preload font to use a preload font weight variable to reduce difference in fonts causing a less intrusive font change.
Before (preload and loaded font difference):
After (preload and loaded font difference):
> v0.100.1 - Update font weight

- CHANGELOG.md
- package.json
- src/js/index.js
- src/js/modules/breakpointHelper.js
- src/js/test/index.test.js
Extension of current breakpointHelper JS to include `withinBreakpoint`.
`withinBreakpoint` is build to mimic our current SCSS breakpoint media queries. 
`withinBreakpoint('>mid')` and will return true or false.
---
> v1.3.0 - within breakpoint method

- CHANGELOG.md
- package.json
- src/scss/components/optional/_toast.scss
- src/scss/objects/_form-toggle.scss
- Improved a11y focus states on `.o-formToggle`.
- Updated `.o-formToggle` checked state to reflect new design.
- Fixed icon showing on hover.
- Fixed border updating when checked (missing content in pseudo).
Before:
After:
> v1.8.0 - form toggle a11y and states

- CHANGELOG.md
- package.json
- src/scss/components/optional/_ratings.scss
- Move small star rating styles into mixin to reduce duplication
- Addition of pixel density ratio media query and override of spacing var within
On high (3+) pixel density ratio devices the small sized ratings would render ~ 6.1 stars
Before:
After:
> v1.9.0 - Star rating size issue on high DPR devices

- CHANGELOG.md
- package.json
- src/scss/components/optional/_listings.scss
- src/scss/objects/_form-toggle.scss
- addition of display none to has-noItems class within listing component
Before (when `has-noItems` applied to an elm with bg colour):
> v1.11.0 - listing `has-noItems` style

- CHANGELOG.md
- package.json
- src/scss/components/optional/_ratings.scss
- Fixed star rating SVG rendering on IE11 by setting the background size to the set size of the SVG.
background SVG's in IE11 don't like a background size of contain 
Before:
After:
> v1.14.0 - IE11 star rating rendering

- .babelrc
- CHANGELOG.md
- package.json
- src/scss/_dependencies.scss
- src/scss/components/optional/_cuisines-widget.scss
- yarn.lock
- Styles for `c-cuisinesWidget`.
- Babel resolution set to fix Travis build
- Minor package updates
- Babel 7 dependencies removed from package.json (as now installed as part of gulp-build-fozzie).
Grid with 6 elements:
[![Image from Gyazo](https://i.gyazo.com/323381ad75eb00c5430fb9dfe1b16a39.gif)](https://gyazo.com/323381ad75eb00c5430fb9dfe1b16a39)
Grid with 5 elements:
[![Image from Gyazo](https://i.gyazo.com/7191ebaee995ec43df9f949f5429eecb.gif)](https://gyazo.com/7191ebaee995ec43df9f949f5429eecb)
- [ + ] This PR has been checked with regard to our brand guidelines
- [ + ] UI Documentation has been [created|updated]
- [ + ] This code has been checked with regard to our accessibility standards
- [ + ] Chrome
- [ + ] Firefox
- [ + ] Safari
- [ + ] Edge
- [ + ] Internet Explorer 11
- [ + …
> v1.17.0 - styles for cuisines widget

- CHANGELOG.md
- package.json
- src/scss/_dependencies.scss
- src/scss/components/optional/_apps-banner.scss
- Styles for `c-appsBanner`.
In future for mobile there will be only one "download the app" button depending on what device you are + image will be different.
[![Image from Gyazo](https://i.gyazo.com/8457d05568fa6110f1bc089e589283a8.gif)](https://gyazo.com/8457d05568fa6110f1bc089e589283a8)
- [ + ] This PR has been checked with regard to our brand guidelines
- [ + ] UI Documentation has been [created|updated]
- [ + ] This code has been checked with regard to our accessibility standards
- [ + ] Chrome
- [ + ] Firefox
- [ + ] Safari
- [ + ] Edge
- [ + ] Internet Explorer 11
- [ + ] Mobile (iPhone/Android - via responsive browser mode)
> v1.18.0 add styles for c-appsBanner

- CHANGELOG.md
- package.json
- src/scss/objects/_buttons.scss
The height of the button is currently 48px instead of the proposed 40px. This change decreases the vertical padding to fix this.
[Zeplin](https://app.zeplin.io/project/58e7554e0352f8ef2215f131/screen/5ab53161419dc1979f6d51de)
> v1.20.0 - Updated vertical padding to button

- CHANGELOG.md
- package.json
- src/scss/components/optional/_content-title.scss
- src/scss/components/optional/_listings.scss
- Adjusted dates in changelog.
- Removed height on `c-contentTitle-icon` to fix icon alignment.
- `white-space: initial` to `.c-listing-item-detailsRow-text` to adjust line wrapping.
> v1.24.1 - Alignment tweeks

- CHANGELOG.md
- package.json
- src/scss/components/optional/_cuisines-widget.scss
- Rewrite `c-cuisinesWidget` to use css grid instead of flex
The block looks the same as with flexboxes, just fixed the Edge width calculation problem and reduce a little bit amount of styles
[![Gif from Gyazo](https://i.gyazo.com/c0df29a69863fb93c97fe8c405c2000e.gif)](https://gyazo.com/c0df29a69863fb93c97fe8c405c2000e)
> v1.30.0 - Rewrite c-cuisinesWidget to use css grid instead of flex

- CHANGELOG.md
- package.json
- src/scss/components/optional/_cookie-warning.scss
The cursor type for the button to close the cookie banner did not change on mouseover, but it should be `pointer` to "feel right" to users.
> v1.30.1 - Add pointer cursor for cookie banner close button

- CHANGELOG.md
- package.json
- src/scss/components/optional/_cuisines-widget.scss
- Change class names from `c-cuisinesWidget-grid` and `c-cuisinesWidget-grid--gridOfThree` to `c-cuisinesGrid` and `c-cuisinesGrid--gridOfThree`
> v1.31.0 Css class names fix for cuisines block

- CHANGELOG.md
- package.json
- src/scss/components/optional/_page-banner.scss
- Add more media breakpoints to `c-pageBanner--tall`
> v1.33.0 add more media breakpoints to c-pageBanner--tall

- CHANGELOG.md
- package.json
- src/scss/components/optional/_cuisines-widget.scss
- Small style amends to `c-cuisinesGrid--gridOfThree`
Replaced grid-gap with margins for better handling less than 6 items grid because if IE explicit grid rule
> v1.34.0 Small style amends to c-cuisinesGrid--gridOfThree

- CHANGELOG.md
- package.json
- src/scss/components/optional/_cookie-warning.scss
Fix cookie banner text flow, remove unnecessary CSS and simplify using scss syntax
CSS change only, no HTML.
> v1.37.0 - Fix cookie banner text flow

- CHANGELOG.md
- package.json
- src/scss/components/optional/_apps-banner.scss
- src/scss/components/optional/_cookie-warning.scss
The app component that is shown when a user is not logged in was a bit unbalanced on mobile. I've added some left padding and adjusted the image size to match.
CSS change only, no HTML.
> v1.38.0 - Fix app component padding and image size

- CHANGELOG.md
- package.json
- src/scss/components/optional/_cuisines-widget.scss
- src/scss/components/optional/_order-card.scss
- src/scss/components/optional/_overflow-carousel.scss
`c-order-card` style amends:
- Restaurant title font-weight should be 500;
- More spacing after order date;
- Order summary text colour should be the same as restaurant title (#333);
- If there is only one line of order summary in one tile, total amount should still be on lower line than summary, height of this part should be taken from the tallest order summary tile;
- "Order again" part should be always at the bottom, should be always the same height (48px);
`c-cuisinesWidget` underline text on hover state
Before:
After:
> v1.39.0 c-order-card styles amends

- CHANGELOG.md
- package.json
- src/scss/components/optional/_ratings.scss
_Ratings sizing addition and spacing addition._
- `--spacing` modifier to ratings. addition of `--default--scaleUp` size to ratings
(Rating `default--scaleUp` size with `--spaced` modifier applied)
> v1.43.0 - ratings additions

- CHANGELOG.md
- package.json
- src/scss/components/optional/_user-message.scss
`grid-template-columns` does not work on IE11 so I've replaced `display: grid` with `display: flex`.
> v1.47.1 - Fix IE11 styles

- CHANGELOG.md
- package.json
- src/scss/components/optional/_apps-banner.scss
Fixes the issue with NO/DK banner and centre the banner on mobile:
Before:
After:
Browsers tested:
IE11
Chrome
Firefox
Safari
> v1.48.0 apps banner styling adjustments

- CHANGELOG.md
- package.json
- src/scss/components/optional/_fullscreen-pop-over.scss
- src/scss/components/optional/_overflow-carousel.scss
- Addition of modifier to overflow carousel to include a mid version.
- also split out some code into mixins to avoid duplication
- Update fullScreenPopOver to not exclude any breakpoints
No _real_ change.
> v1.53.0 - Updates to overflow carousel and full screen popover

- CHANGELOG.md
- package.json
- src/scss/components/optional/_page-banner.scss
- `c-pageBanner--loading` modifier to remove margin whilst images are loading.
- Increased margin top for on images on wide screens for `c-pageBanner--narrow`.
> v1.61.0 — Updating page banner styles.

- CHANGELOG.md
- package.json
- src/scss/components/optional/_listings.scss
- remove animation from the c-listing-item-header for improved page performance
> v1.62.1 - Removal of animation

- CHANGELOG.md
- package.json
- src/scss/components/optional/_modal.scss
- `c-modal-title--spacing` modifier.
- `c-modal-content--flush` now only removes padding.
- `c-modal-content--scrollable` renamed to `c-modal-content-scrollable` as it is applied to a child of `c-modal-content`.
- Casing on `c-modal--fullPage--belowMid` updated.
> v1.63.0 — Updated `c-modal` styles.

- CHANGELOG.md
- package.json
- src/scss/base/_typography.scss
- src/scss/settings/_variables.scss
Simple update to the CSS font fallback cascade using more visually harmonious fallbacks, e.g. sans-serif system fallbacks for all sans-serif Web fonts (likewise serif-for-serif).
> v1.66.0 Improved CSS fallback font cascade

- CHANGELOG.md
- package.json
- src/scss/settings/_variables.scss
- update unit intervals to fix safari rounding issue
> v1.67.0 - update unit intervals to fix safari rounding issue

- CHANGELOG.md
- package.json
- src/scss/components/_media-element.scss
- src/scss/trumps/_utilities.scss
- Styles for `.c-mediaElement-infoLink`, `$mediaElement-img-borderRadius` and `.c-mediaElement--fullstack--negativeTop` for menuweb UI designs
> v1.71.0 -- Updating mediaElement component

- CHANGELOG.md
- package.json
- src/scss/components/optional/_menu.scss
Currently when using the `.c-menu--expandable--expanded` css classes it applies the `overflow` css attribute which applies an empty scrollbar for non-scrollable elements.
This creates this visual effect:
By setting it to overflow-y only it will stop the X axis being scrollable and allow the Y axis to be scrollable
> v1.75.1 stop horizontal navbar appearing on vertical dropdowns

- CHANGELOG.md
- package.json
- src/scss/components/optional/_order-card.scss
Small tweaks to orderCard for the Your Favourites experiment, will not affect live implementation
> v1.77.0 - Update orderCard styling for your Favourites experiment

- CHANGELOG.md
- package.json
- src/scss/components/optional/_modal.scss
- `max-height` on `.c-modal-content-scrollable` to prevent locking on iOS
> v1.81.0 - Removed max-height for iOS

- CHANGELOG.md
- package.json
- src/scss/components/optional/_badges.scss
- src/scss/components/optional/_modal.scss
- Reverted `max-height` change to `.c-modal-content-scrollable` as it prevents scrolling on small screen devices.
- Use explicit value for rounded badge border radius.
> v1.83.0 - Revert max height change to fix scrolling issue.

- CHANGELOG.md
- package.json
- src/scss/components/optional/_overflow-carousel.scss
- src/scss/trumps/_rwd.scss
New helper to `_rwd.scss` for hiding items on tiny devices
[Relevant Pull Request with zeplin attached](https://jira.just-eat.net/browse/CCS-218)
The page banner picture needs to be hidden on 375px  (and lower) devices
> v1.88.0: New helper to _rwd.scss for hiding items on tiny devices

- CHANGELOG.md
- package.json
- src/js/modules/stopFoit/test/index.test.js
- src/js/test/index.test.js
- src/scss/components/optional/_modal.scss
- src/scss/components/optional/_overflow-carousel.scss
- yarn.lock
- Reduce motion query to `c-modal--popUp` which disables transition if user has setting enabled.
- Modal close button styles.
- `c-modal--popUp--belowMid` modifier changed to `c-modal--popUp`.
- Switch `js-test-budy` for `@justeat/js-test-buddy`.
- Updated npm dependencies.
- Unused `c-modal-actions--raised` & `c-modal-actions--fixed` classes.
- `c-modal--popUp` now applies transition correctly.
- Ignore test files when transpiling with Babel.
> v1.89.0 - Updating modal styles & npm dependencies.

- .babelrc
- .eslintrc
- .eslintrc.js
- .github/CODEOWNERS
- .travis.yml
- CHANGELOG.md
- babel.config.js
- jest.config.js
- package.json
- yarn.lock
- **Breaking** Support for Node 8 has been removed. Now only tested in Node v10 and v12.
- `espree` resolution removed as no longer needed.
- `gulp` removed from dependency list – not needed as it comes down as a dependency of `gulp-build-fozzie`.
- Updated to use `gulp-build-fozzie` v10 (which uses `gulp` v4).
- Babel and ESLint configs updated in line with current recommendations.
- Browserslist updated to use shared configuration.
> v2.0.0 - Updating configs and gulp-build-fozzie dependency

- CHANGELOG.md
- package.json
- src/scss/components/optional/_modal.scss
- Updated `c-modal` max-width to an even number as odd-numbered widths cause text to become blurry in some browsers.
> v2.1.0 - Updated modal max width.

- CHANGELOG.md
- package.json
- yarn.lock
- Bump to `fozzie-colour-palette` version.
> v3.0.0-beta.1 – Bump to `fozzie-colour-palette` version

- CHANGELOG.md
- package.json
- src/scss/components/optional/_ratings.scss
_Update review stars in Menulog theme to new brand orange. This change is dependent on `f-icons` v1.34.0_
> v3.0.0-beta.2 - Add styles for Menulog review stars

- CHANGELOG.md
- package.json
- src/scss/_dependencies.scss
- src/scss/base/_layout.scss
- src/scss/base/_typography.scss
- src/scss/components/_cards.scss
- src/scss/components/_media-element.scss
- src/scss/components/optional/_cuisines-widget.scss
- src/scss/components/optional/_fullscreen-pop-over.scss
- src/scss/components/optional/_listings-skeleton.scss
- src/scss/components/optional/_listings.scss
- src/scss/components/optional/_menu.scss
- src/scss/components/optional/_order-card.scss
- src/scss/components/optional/_ratings.scss
- src/scss/components/optional/_toast.scss
- src/scss/objects/_buttons.scss
- src/scss/objects/_form-controls.scss
- src/scss/objects/_form-toggle.scss
- src/scss/objects/_lists.scss
- src/scss/objects/_tables.scss
- src/scss/settings/_theme.scss
- src/scss/settings/_variables.scss
- src/scss/trumps/_utilities.scss
- yarn.lock
- All references to `grey--lightest` changed to `grey--lighter` (to match new colour palette).
- All references to `grey--lighter` changed to `grey--light` (to match new colour palette).
- All references to old colours that are no longer part of the new palette updated to new colour variables.
- Glaze and Menulog colour overrides removed.
> v3.0.0-beta.5 - Updating default colour palette to new JET colour scheme

- CHANGELOG.md
- package.json
- src/scss/components/_cards.scss
- src/scss/components/optional/_fullscreen-pop-over.scss
- src/scss/components/optional/_menu.scss
- src/scss/objects/_form-controls.scss
- yarn.lock
- Updating various uses of grey across components and updating `fozzie-colour-palette` version with new alias colours for default text and borders.
> v3.0.0-beta.8 - Updating various uses of grey across components

- CHANGELOG.md
- package.json
- src/scss/objects/_form-toggle.scss
- Updating `c-formToggle` border colours (uses knocked back border, rather than default border colour).
> v3.0.0-beta.9 - c-formToggle border update

- CHANGELOG.md
- package.json
- Bumping version to `v3` as colour changes should now be stable (and to enable us to prep for v4 which will be font changes).
> v3.0.0 – Moving v3 out of beta

- CHANGELOG.md
- package.json
- src/scss/base/_typography.scss
- Added `font-family` property back for headings as the font-family can be overridden by the reset styles if headings are children of elements such as buttons.
> v4.1.0 - Added font-family property to headings.

- CHANGELOG.md
- package.json
- src/scss/base/_layout.scss
- `:focus-visible` styles which provide more control over when focus outlines are displayed. This allows us to only show the focus outlines when using a keyboard. 
> show focus styles only when they are needed, using the same heuristic that the browser uses to decide whether to show the default focus indicator
See this article for more info - https://matthiasott.com/notes/focus-visible-is-here.
> v4.2.0 - Only show focus styles when needed.

- CHANGELOG.md
- package.json
- src/scss/_dependencies.scss
- src/scss/components/optional/_loading-indicator.scss
v5.0.0-beta.3
*February 16, 2021*
- Loading indicator which was in version 4 with an optional size
> v5.0.0-beta.3 - Add loading indicator component

- CHANGELOG.md
- jest.config.js
- package.json
- src/scss/_dependencies.scss
- src/scss/base/_typography.scss
- src/scss/components/_breadcrumbs.scss
- src/scss/components/_cards.scss
- src/scss/components/_media-element.scss
- src/scss/components/optional/_badges.scss
- src/scss/components/optional/_cookie-warning.scss
- src/scss/components/optional/_cuisines-widget.scss
- src/scss/components/optional/_fullscreen-pop-over.scss
- src/scss/components/optional/_listings-skeleton.scss
- src/scss/components/optional/_listings.scss
- src/scss/components/optional/_loading-indicator.scss
- src/scss/components/optional/_menu.scss
- src/scss/components/optional/_modal.scss
- src/scss/components/optional/_order-card.scss
- src/scss/components/optional/_page-banner.scss
- src/scss/components/optional/_toast.scss
- src/scss/components/optional/_user-message.scss
- src/scss/objects/_body.scss
- src/scss/objects/_buttons.scss
- src/scss/objects/_form-controls.scss
- src/scss/objects/_form-toggle.scss
- src/scss/objects/_lists.scss
- src/scss/objects/_tables.scss
- src/scss/trumps/_utilities.scss
- yarn.lock
- Moved from using `fozzie-colour-palette` to `pie-design-tokens`.
- Colour variables transitioned:
- `$black` > `$color-black`
- `$white` > `$color-white`
- `$grey--light` > `$color-grey-30`
- `$brand--orange` > `$color-orange-30`
- `$orange` > `$color-orange`
- `$orange-dark` > `$color-orange` & darken(4%)
- `$orange-darkest` > `$color-orange` & darken(10%)
- `$orange--aa` > `$color-orange-60`
- `$orange--offWhite` > `$color-orange-10`
- `$blue` > `$color-blue`
- `$blue--offWhite` > `$color-blue-10`
- `$blue--offWhite--dark`> `$color-blue-10` & darken(4%)
- `$blue--offWhite--darkest`> `$color-blue-10` & darken(10%)
- `$red` > `$color-red`
- `$green` > `$color-green`
- `$green--offWhite` > `$color-green-10`
- `$yellow--offWhite` > `$color-yellow-10`
- `$grey--offWhite` > `$color-grey-10` …
> v5.0.0-beta.4 – Updating colours to use new pie-design-tokens variable equivalents

- CHANGELOG.md
- src/scss/base/_typography.scss
- src/scss/components/optional/_content-header.scss
- src/scss/components/optional/_content-title.scss
- src/scss/components/optional/_fullscreen-pop-over.scss
- src/scss/components/optional/_menu.scss
- src/scss/components/optional/_order-card.scss
- src/scss/objects/_lists.scss
- src/scss/settings/_variables.scss
- Updated type-map with new typography variables for font-size and line-height.
- Typography variables transitioned:
- `$font-weight-base` > `$font-weight-regular`
- `$font-weight-bold` definition was removed as it now comes from pie-design-tokens.
> v5.0.0-beta.5 - Import typography design tokens into Fozzie

- CHANGELOG.md
- package.json
- src/scss/base/_layout.scss
- src/scss/base/_typography.scss
- src/scss/components/_cards.scss
- src/scss/components/_media-element.scss
- src/scss/components/optional/_fullscreen-pop-over.scss
- src/scss/components/optional/_listings.scss
- src/scss/components/optional/_menu.scss
- src/scss/objects/_body.scss
- src/scss/objects/_buttons.scss
- src/scss/objects/_form-controls.scss
- src/scss/objects/_links.scss
- src/scss/objects/_tables.scss
- src/scss/trumps/_utilities.scss
- Underlined hover and focus state for `.o-link--noDecoration`.
- More colour variables transitioned:
- `$color-bg` > `$color-background-default`
- `$color-text` > `$color-content-default`
- `$color-headings` > `$color-content-default`
- `$color-link-default` > `$color-content-link`
- `$color-border` > `$color-border-strong`
- `$color-link-hover` > `$color-content-link` & darken(4%)
- `$color-link-active` > `$color-content-link` & darken(6%)
> v5.0.0-beta.6 - more color vars transition + link styles changes

- CHANGELOG.md
- package.json
- src/scss/components/_alerts.scss
- src/scss/objects/_buttons.scss
- src/scss/trumps/_utilities.scss
- yarn.lock
- More colour variables transitioned:
- `$color-secondary` > `$color-blue`
- `$color-text--hint` > `$color-grey-40`
- `$color-text--success` > `$color-content-positive`
- `$color-text--danger` > `$color-content-error`
- `$color-text--warning` > `$color-content-brand-strong`
- `$color-focus-outline` > `$color-focus`
- Updated `f-utils` to v2.0.0
> v5.0.0-beta.7 - more pie design tokens colour vars transitioned

- CHANGELOG.md
- package.json
- src/scss/components/optional/_loading-indicator.scss
v5.0.0-beta.8
*June 4, 2021*
- Mixin in `loading-indicator` to be able to customise the colours of the spinner.
_Note: tested by `yalc'ing` these changes to `fozzie-components`_
> v5.0.0-beta.8 - Adding a mixin in loading-indicator to be able to customise the colours of the spinner.

- CHANGELOG.md
- package.json
- src/scss/base/_layout.scss
- src/scss/components/_alerts.scss
- src/scss/objects/_buttons.scss
- src/scss/objects/_form-controls.scss
- src/scss/objects/_tables.scss
- src/scss/trumps/_utilities.scss
- More colour variables transitioned:
- `$color-headings--highlight` > `$color-content-brand`
- `$color-bg--accept` > `$color-support-positive-02`
- `$color-bg--notification` > `$color-support-warning-02`
- `$color-bg--error` > `$color-support-error-02`
- `$color-disabled` > `$color-disabled-01`
- `$color-bg--component` > `$color-container-default`
- Changed some global tokens to aliases
> v5.0.0-beta.9 - aliases instead of global vars + missed vars update

- CHANGELOG.md
- package.json
- src/scss/settings/_variables.scss
As per slack discussion a while ago, this chage fixes `em` scaling on some resolutions.
> v4.5.1 Fixed em scaling

- CHANGELOG.md
- package.json
- src/scss/settings/_variables.scss
> v4.5.2 fixed the linter error

- CHANGELOG.md
- package.json
- src/scss/_dependencies.scss
- src/scss/_templates.scss
- src/scss/base/_normalize.scss
- yarn.lock
- Move normalize styles from base to optional. We had to copy the styles straight into the project to be able to make them optional wrapping them into a mixin.
!!Note: If you don't use `$includeBaseFramework` or `$includeMinimalFramework` vars and want to have normalize styles in you project, you need to `@include normalize()` mixin starting from this version.
> v5.1.0 - move normalize styles from base to optional

- CHANGELOG.md
- package.json
- src/scss/base/_typography.scss
- src/scss/settings/_variables.scss
- `$font-size-base` to use `$font-paragraph-01`(16px) instead of  `$font-paragraph-02`(14px).
- separate font-sizes for mobile and desktop screen sizes for `h3,.gamma,h4,.delta,h5,.epsilon` headings.
> v6.0.0-beta.2 - more typography changes for ICING

- CHANGELOG.md
- package.json
- src/scss/base/_typography.scss
- src/scss/objects/_buttons.scss
- Button styles in line with icing phase 2.
Now button modifiers are:
- Btn Background Colour modifiers: `o-btn--primary`, `o-btn--secondary`, `o-btn--outline`, `o-btn--ghost`.
- Btn Size Modifiers: `o-btn--sizeLarge`, `o-btn--sizeSmall`, `o-btn--sizeXSmall`.
- Btn Layout Modifiers: `o-btn--block`, `o-btn--wide`, `o-btn--icon`, `o-btn--fullWidth`, `o-btn--disabled`.
- Moved font-family declaration from the button component styles to typography styles.
> v6.0.0-beta.4 - new button styles for icing phase 2

- CHANGELOG.md
- package.json
- src/scss/components/_breadcrumbs.scss
- src/scss/settings/_variables.scss
- `belowMid` z-index value.
- Breadcrumb "pill" modifier styles to ensure alignment and colours are correct.
> v6.0.0-beta.6 - Breadcrumb style updates.

- CHANGELOG.md
- package.json
- src/scss/base/_typography.scss
- src/scss/components/_breadcrumbs.scss
- src/scss/components/_cards.scss
- src/scss/components/_media-element.scss
- src/scss/components/optional/_badges.scss
- src/scss/components/optional/_ratings.scss
- `c-card--info` component modifier.
- `c-rating-description` component modifier.
- Set default paragraph size to match base font-size.
- Card border colour matches PIE designs.
- `c-mediaElement--fullstack--negativeTop` modifier top margin updated.
- Badge component font-size explicitly set.
- `c-badge--indicator` modifier colours updated.
- Breadcrumb icon size.
> v6.0.0-beta.7 - Component style updates.

- package.json
I messed up the npm publish for `v6.0.0-beta.7` by merging the last PR into `master` on my machine instead of `v6.0.0-icing` and then pushing to npm 🙈 
Bumping the version to push the correct changes to npm.
Note that if referencing `v6.0.0-beta.7` you'll likely see errors with variables not being found.
> #trivial fozzie@v6.0.0-beta.8 - Version bump

- CHANGELOG.md
- package.json
- src/scss/base/_layout.scss
- src/scss/base/_typography.scss
- src/scss/components/_alerts.scss
- src/scss/components/_breadcrumbs.scss
- src/scss/components/_cards.scss
- src/scss/components/_media-element.scss
- src/scss/components/optional/_apps-banner.scss
- src/scss/components/optional/_content-header.scss
- src/scss/components/optional/_content-title.scss
- src/scss/components/optional/_cookie-warning.scss
- src/scss/components/optional/_cuisines-widget.scss
- src/scss/components/optional/_fullscreen-pop-over.scss
- src/scss/components/optional/_listings-skeleton.scss
- src/scss/components/optional/_listings.scss
- src/scss/components/optional/_menu.scss
- src/scss/components/optional/_modal.scss
- src/scss/components/optional/_order-card.scss
- src/scss/components/optional/_overflow-carousel.scss
- src/scss/components/optional/_user-message.scss
- src/scss/objects/_buttons.scss
- src/scss/objects/_form-controls.scss
- src/scss/objects/_form-toggle.scss
- src/scss/objects/_lists.scss
- src/scss/objects/_tables.scss
- src/scss/settings/_variables.scss
- src/scss/trumps/_utilities.scss
- yarn.lock
- **Breaking** Type map for $spacing to reference pie design tokens.
- If you are using the below mapping values please note they have changed or been removed:
$spacing x 6 = spacing(h) instead of spacing(x6) - Note the size change has gone from 48px > 56px.
$spacing x 9 - Has been removed - Please map to the next value up or down e.g spacing(j) or spacing(i).
| Old map usage | New map usage |
| ----- | ----- |
| spacing(x0.5) | $spacing(a) |
| spacing(base) | $spacing(b) |
| spacing(x1.5) | $spacing(c) |
| spacing(x2) | $spacing(d) |
| spacing(x3) | $spacing(e) |
| spacing(x4) | $spacing(f) |
| spacing(x5) | $spacing(g) |
| spacing(x6) | $spacing(h) |
| spacing(x7) | $spacing(h) |
| spacing(x8) | $spacing(i) |
| spacing(x9) | Removed, replace with closet size up or down |
| spacing(x10) …
> V7.0.0 update tokens

- CHANGELOG.md
- package.json
- yarn.lock
- f-utils version to fix `map.merge` lint error.
> v7.3.0 - Bump f-utils package.

- CHANGELOG.md
- package.json
- yarn.lock
https://github.com/justeat/f-utils/pull/15
- `dart-sass` deprecation warnings.
> v7.4.0 - Bump f-utils version for dart migration.

- CHANGELOG.md
- package.json
- src/scss/components/optional/_cuisines-widget.scss
- src/scss/components/optional/_fullscreen-pop-over.scss
- src/scss/components/optional/_listings.scss
- src/scss/components/optional/_menu.scss
- src/scss/components/optional/_modal.scss
- src/scss/components/optional/_order-card.scss
- src/scss/components/optional/_toast.scss
- src/scss/trumps/_utilities.scss
- box-shadow values now use pie-design-tokens `$elevation` tokens.
- Deprecation warning to the `c-modal` and `orderCard` components.
- box-shadow from hover state of cuisinesWidget component styles.
- `.c-menu--expandable` and `.c-menu--expandable--expanded` classes from menu component styles.
> v7.5.0 - elevation tokens

- CHANGELOG.md
- package.json
- src/scss/_dependencies.scss
- yarn.lock
- Attempting to remove reliance on eyeglass in favour of using sass-loader `includePaths` option to resolve imports to node_modules.
Downside to this will be we are tied to using either webpack or a tool that allows similar functionality through it's resolver options.
> v8.0.0 – Removing reliance on eyeglass for imports

- CHANGELOG.md
- package.json
- yarn.lock
This PR adds Node 16 to the engines property in package.json.
Doing this allows up to upgrade fozzie-components and other repos to Node 16.
Tested locally by switching to Node 16 and running `yarn` / `yarn compile`
Was able to successfully import this version into fozzie-components when using Node 16.
> v8.2.0 - Node 16 compatibility

- CHANGELOG.md
- package.json
- src/scss/tools/mixins/_type.scss
v9.0.0-beta.2
*June 15, 2022*
- Use a `@use` rule for `line-height` function in `_type.scss`
- Remove namespace aliases from `@use` rules in `_type.scss`
> v9.0.0-beta.2 - update @use rules in _type.scss

- CHANGELOG.md
- package.json
- src/scss/tools/functions/_units.scss
- `sass:map` to resolve `map-get` error when using `sass` in comsuming apps.
> v8.3.0 - Add sass:map.

- CHANGELOG.md
- package.json
v8.4.1
*July 06, 2022*
- switch from `prepare` to `prepublishOnly` in package.json scripts
> v8.4.1 - prepublishOnly script

- CHANGELOG.md
- package.json
- src/scss/settings/_color-palette.scss
- src/scss/tools/mixins/_type.scss
- Colour palette references now point to `pie-design-tokens`
> v9.0.2 – Updating colour palette references

- CHANGELOG.md
- package.json
- src/scss/_dependencies.scss
- src/scss/tools/mixins/_index.scss
- src/scss/tools/mixins/_utilities.scss
- src/scss/trumps/_spacing.scss
- src/scss/trumps/_utilities.scss
- Utilities mixin module containing a new `spacing-map` variable and `spacing-classes` mixin which can be used to generate utility classes for each spacing variable.
- Optional spacing trump module which generates margin & padding utility classes.
- `u-noBorder`, `u-noBackground`, and `u-hover--cursor` utility classes.
A bit more detail on the spacing utility classes — these can be included in a project via an optional mixin, similar to [the classes in the utilities module](https://github.com/justeat/fozzie/blob/cea5fac43e8cce521ae8d199a61d1fe5190745c3/src/scss/trumps/_utilities.scss#L273). The difference is that these new classes feed off of our spacing variables and include a class for each spacing e.g.
```css
.u-pad-a {}
.u-pad-b {}
...
.u-pad-a--top {}
.u-pad-b--top {}
... …
```
> v9.1.0 - Adding spacing utility classes.

- CHANGELOG.md
- package.json
- src/scss/_dependencies.scss
- src/scss/tools/_index.scss
- Ordering issue to prevent use & forward from throwing load order errors in consuming apps when using sass `with` syntax.
> v9.2.0 - Fix load order issue

- CHANGELOG.md
- package.json
- src/scss/settings/_include-media.scss
- src/test/scss/fozzie.spec.scss
v9.3.3
*September 1, 2022*
- A basic integration test to catch SCSS errors
> v9.3.3 - catch SCSS errors in test
